spring:
  thymeleaf:
    cache: false
    #数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      #最小空闲链接
      minimum-idle: 5
      #空闲连接最大存活时间 默认600000(十分钟)
      idle-timeout: 1800000
      #最大连接数 默认 10
      maximum-pool-size: 10
      #从连接池返回的自动提交
      auto-commit: true
      #链接最大存活时间 0表示永久存活 默认 1800000(半个小时)
      max-lifetime: 1800000
      #连接池名称
      pool-name: DataHikariCP
      #连接超时时间默认30秒
      connection-timeout: 30000
      #测试连接是否可用的查询语句
      connection-test-query: select 1

#MyBtais-plus 配置
mybatis-plus:
  #配置mapper.xml映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #配置MyBatis数据返回类型的别名(默认别名是类名)
  type-aliases-package: com.xxxx.seckill.pojo

#MyBatis SQL 打印(方法接口所在包，不是Mapper.xml所在包)
logging:
  level:
    com.xxx.seckill.mapper: debug